fn main() {
    // panic!("Uh oh")

    let v = vec![1, 2, 3];

    v[99];

    // use export RUST_BACKTRACE=1
    // to see full unwinding of the error
}
